### PR TITLE
:robot: triggering CI on branch 'redhat-v1.2.2' after synching from upstream/v1.2.2

### PR DESCRIPTION
**Pull request by lance**

### CODE REVIEW

**Review by JasonPowr — APPROVED** [review]
/lgtm

**Comment by lance** [comment]
/override "Red Hat Trusted App Test / backfill-redis / rhtas-stack-1-0-beta-enterprise-contract"
/override "Red Hat Trusted App Pipeline / rekor-cli-on-pull-request"
/override "Red Hat Trusted App Pipeline / rekor-server-on-pull-request"

**Comment by lance** [comment]
/override "Red Hat Trusted App Test / rekor-cli / rhtas-cli-1-0-beta-enterprise-contract"
/override "Red Hat Trusted App Test / rekor-server / rhtas-stack-1-0-beta-enterprise-contract"

**Pull request merged**
