### PR TITLE
add Overlays, update shas, add e2e bits

### PR DESCRIPTION
**Pull request by JasonPowr**
This pr introduces changes needed to allow RHTAP to run E2E tests 

## Comments

- I've updated the shas to the newest versions, should help with some of the EC tests
- The two patch files are responsible for modifying the existing e2e tests by removing all docker-compose elements allowing the tests to run inside RHTAP, and modifying a test that needed Docker to run.

### CODE REVIEW

**Review by lance — COMMENTED** [review]
@JasonPowr this looks great - with one caveat. Currently the update script does not work well with patches. I outlined this in a gdoc recently. It's not ideal, but for the time being (i.e. the tech preview release) can these patches be made instead into overlays?

**Comment by JasonPowr** [comment]
> @JasonPowr this looks great - with one caveat. Currently the update script does not work well with patches. I outlined this in a gdoc recently. It's not ideal, but for the time being (i.e. the tech preview release) can these patches be made instead into overlays?

Yep they can be made in overlays ill update the pr soon :)

**Comment by JasonPowr** [comment]
@lance Ive changed the overlays to patches, and removed the logic for the patches, let me know if this is the best way to do it :)

**Comment by JasonPowr** [comment]
I was trying to run the update script to fix the builds in rhtas, the script still tries to apply the patches in redhat-v1.2.2 and causes an error, so hopefully this should fix this as well

**Review by lance — APPROVED** [review]
/lgtm

**Pull request merged**
