### PR TITLE
chore: update SHAs to the latest for UBI9 go-toolset

### PR DESCRIPTION
**Pull request by lance**
Updates to repoisitory tag 1.19.13-4.1697647145

### CODE REVIEW

**Review by JasonPowr — CHANGES_REQUESTED** [review]
Looks good, just missed one for the test image https://github.com/securesign/rekor/pull/124/files#diff-ce5bb5b25694bdd09dc69ee8b16ee9dd4bf8f48791bb8b312a519a98da773de5R40

**Comment by lance** [comment]
> Looks good, just missed one for the test image https://github.com/securesign/rekor/pull/124/files#diff-ce5bb5b25694bdd09dc69ee8b16ee9dd4bf8f48791bb8b312a519a98da773de5R40

@JasonPowr done - good 👁️

**Review by JasonPowr — APPROVED** [review]
/lgtm

**Pull request merged**
