### PR TITLE
feat: Enable E2E tests in RHTAP for rekor

### PR DESCRIPTION
**Pull request by JasonPowr**
Adds the tasks and changes needed to support E2E tests in RHTAP,

## Comments
Marking this pr as draft until changes are in main

### CODE REVIEW

**Comment by lance** [comment]
@JasonPowr is this still a WIP?

**Comment by JasonPowr** [comment]
Needs a bit of work after the path updates

**Comment by JasonPowr** [comment]
This is all goo now ran into some issues with paths, permissions and auth, but as you can see its running and passing now https://console.redhat.com/preview/application-pipeline/workspaces/rhtas/applications/rhtas-stack-1-0-beta/pipelineruns/rekor-server-on-pull-request-p8f5p

**Review by lance — COMMENTED** [review]
/lgtm
Great work @JasonPowr thank you!

**Pull request merged**
